services:
  postgres:
    image: postgres:17.2-alpine
    container_name: notes-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-note-service-local-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-note-service-local-password}
      POSTGRES_DB: ${POSTGRES_DB:-notes-service}

volumes:
  postgres-data: